### ISSUE TITLE
Revisi 1

### ISSUE THREAD

**Issue by AaEzha** [nengwiwik/pengadaan-perpustakaan#6]
- [ ] import buku bisa dinamis
- [x] satu buku bisa multi jurusan - _26 April 2023_
- [x] listing buku untuk prodi sesuai jurusan
- [x] penerbit upload invoice (di menu Arsip Pengadaan) - _26 April 2023_
- [x] prodi hanya bisa memilih buku, bukan jumlah buku
- [x] hapus form catatan kampus maupun penerbit
- [x] tambah input cover (gambar) dan input ringkasan untuk buku
- [ ] minta redaksi email
- [x] tidak bisa input buku yang sudah pernah dibeli - _26 April 2023_

**Comment by AaEzha** [comment]
setelah pull, jangan lupa jalankan `php artisan migrate` sebab ada beberapa perubahan kolom di database

**Comment by nengwiwik** [comment]
note pak

Pada tanggal Sel, 14 Mar 2023 pukul 05.14 Aa Ezha ***@***.***>
menulis:

**Comment by nengwiwik** [comment]
Oke yah.. belum di migrate fresh kayane deh
